checks:
    javascript: true
build:
  nodes:
    some-node:
      dependencies:
        before:
          - npm ci
          - npm install -g @mockoon/cli

    coverage:
      tests:
        override:
          - command: "npm run mock && npm run github-test"
            coverage:
              file: coverage/clover.xml

              # These formats are supported:
              # clover, cobertura, jacoco, python-cc, ruby-cc, go-cc, lcov
              format: clover
