checks:
  javascript: true
build:
  nodes:
    some-node:
      dependencies:
        before:
          - npm run mock

coverage:
  tests:
    override:
      - command: "npm run github-test"
        coverage:
          file: coverage/clover.xml

          # These formats are supported:
          # clover, cobertura, jacoco, python-cc, ruby-cc, go-cc, lcov
          format: clover
